apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: mini-obs-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.chaos-mesh.org
    chart: chaos-mesh
    targetRevision: "2.6.3"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/owner/mini-obs-platform/HEAD/infra/helm/chaos-mesh/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
