apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: mini-obs-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: "0.71.14"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/owner/mini-obs-platform/HEAD/infra/helm/jaeger/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
