---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-demo
  labels:
    app.kubernetes.io/part-of: mini-obs-platform

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: mini-obs-platform

---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
  labels:
    app.kubernetes.io/part-of: mini-obs-platform

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/part-of: mini-obs-platform

---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
  labels:
    app.kubernetes.io/part-of: mini-obs-platform
